### ISSUE TITLE
Scope the Landing Zone Target State Plan.

### ISSUE THREAD

**Issue by gabrrodriguez** [gabrrodriguez/uklife-lz-prototype#19]
# User Story
As a `user` of the UKLife landing zone, `action`, so that `impact`. 

# Pre-requisites: 
- [ ] _item we need_

# Test Cases: 
- [ ] _how do I validate design_

# Methods of Creation: 
- [ ] _does it have to be done manually or can we use IaC_

# Exit Criteria
- [ ] Successful execution of Test Cases
- [ ] Capture of relevant policies artifacts in this Issue
- [ ] Integration of Procedures into Op Model
- [ ] Costing

**Comment by gabrrodriguez** [comment]
# Phase I

<p align="center">
<img width="450" src="https://github.com/gabrrodriguez/uklife-lz-prototype/assets/126508932/be185b2a-9538-430d-9d76-3f5da2f3a5d6"
</p>

# Phase II
