### ISSUE TITLE
Create Landing Zone Account Structure

### ISSUE THREAD

**Issue by gabrrodriguez** [gabrrodriguez/uklife-lz-prototype#36]
# User Story
As a UKLife Admin, we will need to create/delete/maintain Accounts that align to our Organizational Unit structure, so that we can operate and amend the UKLife Landing Zone structure.

# Pre-requisites: 
- [ ] Landing Zone was successfully deployed [Issue 34](https://github.com/gabrrodriguez/uklife-lz-prototype/issues/34)
- [ ] Organizational Unit structure was successfully deployed  [Issue 35](https://github.com/gabrrodriguez/uklife-lz-prototype/issues/35)
- [ ] All Organizational Units were successfully registered. [Issue 35](https://github.com/gabrrodriguez/uklife-lz-prototype/issues/35)

# Test Cases: 
- [ ] _how do I validate design_

# Methods of Creation: 
- [ ] _does it have to be done manually or can we use IaC_

# Exit Criteria
- [ ] Successful execution of Test Cases
- [ ] Capture of relevant policies artifacts in this Issue
- [ ] Integration of Procedures into Op Model
- [ ] Costing

**Comment by gabrrodriguez** [comment]
# Architecture

## Reference 
- [ ] [Patterns for organizing your AWS accounts](https://docs.aws.amazon.com/whitepapers/latest/organizing-your-aws-environment/patterns-for-organizing-your-aws-accounts.html)

**Comment by gabrrodriguez** [comment]
# Procedure (Net New Account)

**Comment by gabrrodriguez** [comment]
# Design Considerations 

1. Namespace conflict on *AWS Service Catalog*
> In this instance we have an account named `Network` under the `Infrastructure / Non-Prod` OU & the `Infrastructure / Prod` OU. This is creating a namespace conflict on the AWS Service Catalog which is provisioning the *Product* (CloudFormation Stack). We will need to resolve these namespace conflicts. 

<p align="center">
<img width="450" alt="image" src="https://github.com/gabrrodriguez/uklife-lz-prototype/assets/126508932/a803937e-27f1-4981-97f5-0d01eb233518">
</p>
